---
- hosts: vmsnew
  become: yes
  tasks:
  - name: mkdir if not exists
    ansible.builtin.file:
      path: /home/dusk/tmpdir
      state: directory
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://mirror.yandex.ru/libreoffice/libreoffice/stable/7.5.9/deb/x86_64/LibreOffice_7.5.9_Linux_x86-64_deb_langpack_ru.tar.gz
      dest: /home/dusk/tmpdir
      remote_src: yes